name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '*/6 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Fetch latest data
      run: |-
        curl 'https://mc-api.dribl.com/api/fixtures?date_range=default&season=3vmZpnGKq5&competition=R3NPZlPdr4&league=8nm7kPnLmO&club=RwNl4geNjr&tenant=kbam1QjmwX' \
          | jq > fixtures.json
    - name: Update ICS file
      run: |-
          bash parse-fixtures.sh > game-calendar-2024.ics
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
